{% set version = "9.6.1" %}
{% set sha256 = "e5101e0a49141fc12a7018c6dad594694d3a3325f5ab71e93e0e51bd94e51fcd" %}

package:
  name: postgresql
  version: {{ version }}

source:
  fn: postgresql-{{ version }}.tar.bz2
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - fix_libraries_win.patch  # [win]
    - timezone.patch  # [win and (py >= 35)]
    # https://www.postgresql.org/message-id/attachment/43919/0002-Support-parallel-build-with-MSBuild.patch
    - symbol_tempfile.patch  # [win]

build:
  number: 3
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py >= 35]

requirements:
  build:
    - m2-bison          # [win]
    - m2-diffutils      # [win]
    - m2-flex           # [win]
    - openssl 1.0.*
    - perl    5.22.2.1  # [win]
    - posix   # [win]
    - python
    - vc   9  # [win and py27]
    - vc  14  # [win and py >= 35]
    - zlib 1.2.*
    - krb5
  run:
    - openssl 1.0.*
    - vc   9  # [win and py27]
    - vc  14  # [win and py >= 35]
    - zlib 1.2.*
    - krb5

test:
  commands:
    - pg_config
    - postgres --help
    - conda inspect linkages postgresql  # [linux]
    - conda inspect objects postgresql   # [osx]

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  summary: 'PostgreSQL is a powerful, open source object-relational database system.'

extra:
  recipe-maintainers:
    - gillins
    - msarahan
    - ocefpaf
