{% set version = "9.6.3" %}
{% set sha256 = "1645b3736901f6d854e695a937389e68ff2066ce0cde9d73919d6ab7c995b9c6" %}

package:
  name: postgresql
  version: {{ version }}

source:
  fn: postgresql-{{ version }}.tar.bz2
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - fix_libraries_win.patch  # [win]
    # https://www.postgresql.org/message-id/attachment/43919/0002-Support-parallel-build-with-MSBuild.patch
    - symbol_tempfile.patch  # [win]

build:
  skip: True  # [win]
  number: 3
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - python
    - m2-bison  # [win]
    - m2-diffutils  # [win]
    - m2-flex  # [win]
    - openssl 1.0.*
    - perl 5.22.2.1  # [win]
    - posix  # [win]
    - readline  6.2.* # [not win]
    - zlib 1.2.*
    - krb5  # [not osx]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and (py35 or py36)]
  run:
    - postgresql-server {{ version }}

outputs:
    - name: postgresql-client
      requirements:
        - openssl 1.0.*
        - readline  6.2.* # [not win]
        - zlib 1.2.*
        - krb5  # [not osx]
        - vc 9  # [win and py27]
        - vc 10  # [win and py34]
        - vc 14  # [win and (py35 or py36)]
      script: client-install.py
      test:
        script: client-test.sh

    - name: postgresql-server
      requirements:
        - postgresql-client {{ version }}
      script: server-install.py
      test:
        script: server-test.sh

#test:
#  commands:
#    - conda inspect linkages postgresql  # [not win]
#    - conda inspect objects postgresql  # [osx]

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  license_file: COPYRIGHT
  summary: 'PostgreSQL is a powerful, open source object-relational database system.'

extra:
  recipe-maintainers:
    - gillins
    - msarahan
    - ocefpaf
    - mariusvniekerk
