{% set version = "16.8" %}
{% set pqver = '.'.join(("5", version.split('.')[0])) %}

package:
  name: postgresql-split
  version: {{ version }}

source:
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: 9468083a56ce0ee7d294601b74dad3dd9fc69d87aff61f0a9fb63c813ff7efd8
  patches:
    - patches/0001-fix-win-zlib-name.patch
    - patches/0002-disable-new-dtags.patch
    - patches/fix_gss_win64.patch  # [win64]
    - patches/0004-fix-windows-openssl-links-for-openssl-1.1.1.patch
    - patches/fix_gssapi_setenv_win.patch  # [win]
    - patches/fix_auth_setenv_win.patch  # [win]
    - patches/fix_x509_name_win.patch  # [win]
    - patches/fix_mac10_9_clock_realtime.patch  # [osx]

build:
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make                       # [unix]
    - m2-bison         # [win]
    - m2-diffutils     # [win]
    - m2-flex          # [win]
    - perl 5.*         # [win]
    - posix            # [win]
    - pkg-config       # [unix]
  host:
    - libxml2
    - libxslt
    - krb5
    - openssl
    - readline        # [not win]
    - zlib
    - vc              # [win]
    - libuuid         # [not win]
    - tzcode          # [not win]
    - tzdata          # [not win]
  run:
    - krb5
    - openssl
    - readline        # [not win]
    - tzcode          # [not win]
    - tzdata          # [not win]

outputs:
  - name: postgresql
    build:
      run_exports:
        - {{ pin_subpackage('libpq') }}
    requirements:
      build:
        # solely for sake of lining up vc versions and other runtimes
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - perl 5.*             # [win]
        - make                 # [unix]
        - pkg-config           # [unix]
      host:
        # these are here for sake of run_exports taking effect
        - krb5
        - openssl
        - readline         # [not win]
        - tzcode          # [not win]
        - tzdata          # [not win]
        - zlib
        - libxml2
        - {{ pin_subpackage('libpq', exact=True) }}
      run:
        - {{ pin_subpackage('libpq', exact=True) }}
        - tzcode          # [not win]
        - tzdata          # [not win]

    test:
      commands:
        - postgres --help
        # run a simple initdb check on unix
        - export TEST_DIR=./test_postgres                       # [unix]
        - initdb -D $TEST_DIR                                   # [unix]
        - pg_ctl -D $TEST_DIR -l logfile start || cat ./logfile # [unix]
        - pg_ctl -D $TEST_DIR stop                              # [unix]
        # Make sure that postgres contains `palloc0` symbol
        - nm -D $(which postgres) | grep -q palloc0 || exit 1   # [linux]

      requirements:
        - binutils   # [linux]
    script: install_db.sh  # [unix]
    script: install_db.bat  # [win]
    about:
      summary: PostgreSQL is a powerful, open source object-relational database system.
      license: PostgreSQL
      license_file: COPYRIGHT

  - name: postgresql-plpython
    build:
      run_exports:
        - {{ pin_subpackage('postgresql-plpython') }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        # solely for sake of lining up vc versions and other runtimes
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - perl 5.*             # [win]
        - make                 # [unix]
        - pkg-config           # [unix]
      host:
        # these are here for sake of run_exports taking effect
        - krb5     # [not osx]
        - openssl
        - zlib
        - {{ pin_subpackage('postgresql', exact=True) }}
        - python
        - libxml2
        - libxslt
        - vc  # [win]
        - libuuid         # [not win]
      run:
        - {{ pin_subpackage('postgresql', exact=True) }}
        - python
    script: install_plpython.sh  # [unix]
    test:
      commands:
    about:
      summary: The plpythonu postgresql extension
      license: PostgreSQL
      license_file: COPYRIGHT

  - name: libpq
    build:
      run_exports:
        - {{ pin_subpackage('libpq') }}
    requirements:
      build:
        # solely for sake of lining up vc versions and other runtimes
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - perl 5.*               # [win]
        - make                   # [unix]
        - pkg-config             # [unix]
      host:
        # these are here for sake of run_exports taking effect
        - krb5
        - openssl
        - tzcode                 # [not win]
        - tzdata                 # [not win]
    script: install_runtime.sh  # [unix]
    script: install_runtime.bat  # [win]
    test:
      commands:
        - pg_config
        - test -f $PREFIX/lib/libpq.so.{{ pqver }}         # [linux]
        - test -f $PREFIX/lib/libpq.so.5                   # [linux]
        - test -f $PREFIX/lib/libpq.so                     # [linux]
        - test -f $PREFIX/lib/libpq.5.dylib                # [osx]
        - test -f $PREFIX/lib/libpq.dylib                  # [osx]
        - IF NOT EXIST %LIBRARY_BIN%\libpq.dll EXIT 1      # [win]
        - IF NOT EXIST %LIBRARY_BIN%\pg_config.exe EXIT 1  # [win]
    about:
      summary: The postgres runtime libraries and utilities (not the server itself)
      license: PostgreSQL
      license_file: COPYRIGHT

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  license_file: COPYRIGHT
  summary: multi-ouput recipe for postgresql

extra:
  recipe-maintainers:
    - akrherz
    - gillins
    - msarahan
    - ocefpaf
    - mariusvniekerk
    - sodre
