{% set version = "9.5.4" %}
{% set sha256 = "cf5e571164ad66028ecd7dd8819e3765470d45bcd440d258b686be7e69c76ed0" %}

package:
  name: postgresql
  version: {{ version }}

source:
  fn: postgresql-{{ version }}.tar.bz2
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - fix_libraries_win.patch  # [win]
    - timezone.patch  # [win and py35]
    # https://www.postgresql.org/message-id/attachment/43919/0002-Support-parallel-build-with-MSBuild.patch
    - symbol_tempfile.patch  # [win]

build:
  number: 2
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - m2-bison         # [win]
    - m2-diffutils     # [win]
    - m2-flex          # [win]
    - openssl 1.0.*
    - perl   >=5.20    # [win]
    - posix    # [win]
    - python
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py35]
    - zlib 1.2.*
  run:
    - openssl 1.0.*
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py35]
    - zlib 1.2.*

test:
  commands:
    - pg_config
    - postgres --help

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  summary: 'PostgreSQL is a powerful, open source object-relational database system.'

extra:
  recipe-maintainers:
    - gillins
    - msarahan
    - ocefpaf
