{% set version = "17.4" %}
{% set pqver = '.'.join(("5", version.split('.')[0])) %}

package:
  name: postgresql-split
  version: {{ version }}

source:
  url: https://ftp.postgresql.org/pub/source/v{{ version }}/postgresql-{{ version }}.tar.bz2
  sha256: c4605b73fea11963406699f949b966e5d173a7ee0ccaef8938dec0ca8a995fe7
  patches:
    - patches/0002-disable-new-dtags.patch
    - patches/fix_gssapi_setenv_win.patch  # [win]
    - patches/fix_auth_setenv_win.patch  # [win]
    - patches/fix_x509_name_win.patch  # [win]
    - patches/fix_mac10_9_clock_realtime.patch  # [osx]

build:
  number: 0
  skip: true  # [not (linux and aarch64)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - gnuconfig        # [unix]
    - meson            # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make             # [unix]
    - pkg-config       # [unix]
    - bison            # [unix]
    - ninja            # [win]
    - perl 5.*         # [win]
    - m2-bison         # [win]
    - m2-diffutils     # [win]
    - m2-flex          # [win]
    - posix            # [win]
    - icu
  host:
    - icu
    - libxml2
    - libxslt
    - krb5
    - openldap        # [not win]
    - openssl
    - lz4-c
    - zlib
    - zstd
    - vc              # [win]
    - libuuid         # [not win]
    - readline        # [not win]
    - tzcode          # [not win]
    - tzdata          # [not win]
  run:
    - krb5
    - openldap        # [not win]
    - openssl
    - readline        # [not win]
    - tzcode          # [not win]
    - tzdata          # [not win]

outputs:
  - name: postgresql
    build:
      run_exports:
        - {{ pin_subpackage('libpq') }}
    requirements:
      build:
        - gnuconfig            # [unix]
        - meson                # [win]
        # solely for sake of lining up vc versions and other runtimes
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make                 # [unix]
        - pkg-config           # [unix]
        - bison                # [unix]
        - ninja                # [win]
        - perl 5.*             # [win]
        - m2-bison             # [win]
        - m2-diffutils         # [win]
        - m2-flex              # [win]
        - posix                # [win]
        - icu
      host:
        # these are here for sake of run_exports taking effect
        - icu
        - libxml2
        - libxslt
        - krb5
        - openldap            # [not win]
        - openssl
        - lz4-c
        - zlib
        - zstd
        - readline            # [not win]
        - tzcode              # [not win]
        - tzdata              # [not win]
        - {{ pin_subpackage('libpq', exact=True) }}
      run:
        - {{ pin_subpackage('libpq', exact=True) }}
        - tzcode              # [not win]
        - tzdata              # [not win]

    test:
      commands:
        - postgres --help
        # check symbols
        - nm -D $(which postgres)  # [linux]
      requirements:
        - binutils   # [linux]
    script: install_db.sh  # [unix]
    script: install_db.bat  # [win]
    about:
      summary: PostgreSQL is a powerful, open source object-relational database system.
      license: PostgreSQL
      license_file: COPYRIGHT

  - name: postgresql-plpython
    build:
      run_exports:
        - {{ pin_subpackage('postgresql-plpython') }}
      # needs packaging help on windows
      skip: true  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - gnuconfig              # [unix]
        - meson                  # [win]
        # solely for sake of lining up vc versions and other runtimes
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make                   # [unix]
        - pkg-config             # [unix]
        - bison                  # [unix]
        - ninja                  # [win]
        - perl 5.*               # [win]
        - m2-bison               # [win]
        - m2-diffutils           # [win]
        - m2-flex                # [win]
        - posix                  # [win]
        - icu
      host:
        # these are here for sake of run_exports taking effect
        - icu
        - libxml2
        - libxslt
        - krb5
        - openldap               # [not win]
        - openssl
        - lz4-c
        - zlib
        - zstd
        - vc                     # [win]
        - libuuid                # [not win]
        - readline               # [not win]
        - {{ pin_subpackage('postgresql', exact=True) }}
        - python
      run:
        - {{ pin_subpackage('postgresql', exact=True) }}
        - python
    script: install_plpython.sh  # [unix]
    test:
      commands:
    about:
      summary: The plpythonu postgresql extension
      license: PostgreSQL
      license_file: COPYRIGHT

  - name: libpq
    build:
      run_exports:
        - {{ pin_subpackage('libpq') }}
    requirements:
      build:
        - gnuconfig              # [unix]
        - meson                  # [win]
        # solely for sake of lining up vc versions and other runtimes
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make                   # [unix]
        - pkg-config             # [unix]
        - bison                  # [unix]
        - ninja                  # [win]
        - perl 5.*               # [win]
        - m2-bison               # [win]
        - m2-diffutils           # [win]
        - m2-flex                # [win]
        - posix                  # [win]
        - icu
      host:
        # these are here for sake of run_exports taking effect
        - icu
        - krb5
        - openldap               # [not win]
        - openssl
        - tzcode                 # [not win]
        - tzdata                 # [not win]
    script: install_runtime.sh  # [unix]
    script: install_runtime.bat  # [win]
    test:
      commands:
        - pg_config
        - test -f $PREFIX/lib/libpq.so.{{ pqver }}         # [linux]
        - test -f $PREFIX/lib/libpq.so.5                   # [linux]
        - test -f $PREFIX/lib/libpq.so                     # [linux]
        - test -f $PREFIX/lib/libpq.5.dylib                # [osx]
        - test -f $PREFIX/lib/libpq.dylib                  # [osx]
        - IF NOT EXIST %LIBRARY_BIN%\libpq.dll EXIT 1      # [win]
        - IF NOT EXIST %LIBRARY_BIN%\pg_config.exe EXIT 1  # [win]
    about:
      summary: The postgres runtime libraries and utilities (not the server itself)
      license: PostgreSQL
      license_file: COPYRIGHT

about:
  home: http://www.postgresql.org/
  license: PostgreSQL
  license_file: COPYRIGHT
  summary: multi-ouput recipe for postgresql

extra:
  recipe-maintainers:
    - akrherz
    - flaviomartins
    - gillins
    - msarahan
    - ocefpaf
    - mariusvniekerk
    - sodre
